### PR TITLE
Remove typings

### PR DESCRIPTION
**Pull request by TheKeithStewart**

### CODE REVIEW

**Comment by tomwayson** [comment]
Thanks for this @kgs916.

One thing I'm wondering is if angular2-esri4-components should declare @types/arcgis-js-api as a _dependency_ instead of a devDependency - then consuming apps would not have to manually add the types to their devDependencies. I searched a bit to see what the norm in the TS community is and (no surprise) it seems like conventions are still forming around this. The most useful discussion I found was this: https://github.com/Microsoft/types-publisher/issues/81#issuecomment-234051338 which indicates that libraries should declare their types as dependencies. However, others on that thread bring up good points about not being able to find any examples of that and the potential for two of an apps dependencies to depend on different versions of a library like the ArcGIS API.

After reading that discussion, I tend to lean towards angular2-esri4-components declaring @types/arcgis-js-api as a dependency instead of a devDependency so that consuming apps such as this do not need to do it themselves. What do you think?

Also cc'ing people that, unlike me, actually use TypeScript: @patrickarlt @dasa @odoe

**Comment by dasa** [comment]
> After reading that discussion, I tend to lean towards angular2-esri4-components declaring @types/arcgis-js-api as a dependency instead of a devDependency so that consuming apps such as this do not need to do it themselves. What do you think?

That sounds good 👍

**Comment by TheKeithStewart** [comment]
Thanks for the feedback @tomwayson and @dasa! I'll make the change in angular2-esri4-components to reflect this and update this PR.

**Comment by TheKeithStewart** [comment]
@tomwayson, I've moved `@types/archgis-js-api` to the dependencies for angular2-esri4-components and added a new commit that removes it from the devDependencies here.

**Review by tomwayson — APPROVED** [review]

**Pull request merged**
